"use client";

import { useEffect, useState, Suspense } from "react";
import { useSearchParams } from "next/navigation";
import { insightService } from "@/services/insightService";
import toast from "react-hot-toast";
import { Skeleton } from "@/components/ui/Skeleton";

interface InsightData {
  summary: string;
  trends: string[];
  anomalies: string[];
  recommendations: string[];
  model: string;
  fromCache?: boolean;
}

interface InsightRecord {
  _id: string;
  datasetId: string;
  summary: string;
  model: string;
  createdAt: string;
}

function InsightsContent() {
  const searchParams = useSearchParams();
  const datasetId = searchParams.get("id");
  const [insight, setInsight] = useState<InsightData | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [history, setHistory] = useState<InsightRecord[]>([]);
  const [showHistory, setShowHistory] = useState(false);

  const generate = async () => {
    if (!datasetId) return;
    setLoading(true);
    setError("");
    setInsight(null);
    try {
      const res = await insightService.generate(datasetId);
      setInsight(res.data.data);
      fetchHistory();
      if (res.data.data.fromCache) toast("Loaded from cache", { icon: "⚡" });
    } catch (err: any) {
      setError(err.error || "Failed to generate insights");
    } finally {
      setLoading(false);
    }
  };

  const fetchHistory = async () => {
    if (!datasetId) return;
    try {
      const res = await insightService.list(datasetId);
      setHistory(res.data.data);
    } catch {
      // silent
    }
  };

  const loadHistoryItem = async (id: string) => {
    try {
      const res = await insightService.get(id);
      setInsight(res.data.data);
      setShowHistory(false);
    } catch {
      toast.error("Failed to load insight");
    }
  };

  useEffect(() => {
    if (datasetId) fetchHistory();
  }, [datasetId]);

  const downloadPDF = () => {
    if (!insight) return;
    let text = "========================================\n";
    text += "       DATALENS AI INSIGHTS REPORT\n";
    text += "========================================\n\n";
    text += `Generated: ${new Date().toLocaleString()}\n`;
    text += `AI Model: ${insight.model}\n\n`;
    text += "--- EXECUTIVE SUMMARY ---\n${insight.summary}\n\n";
    text += "--- KEY TRENDS ---\n" + insight.trends.map((t, i) => `${i + 1}. ${t}`).join("\n") + "\n\n";
    text += "--- ANOMALIES DETECTED ---\n" + insight.anomalies.map((a, i) => `${i + 1}. ${a}`).join("\n") + "\n\n";
    text += "--- RECOMMENDATIONS ---\n" + insight.recommendations.map((r, i) => `${i + 1}. ${r}`).join("\n") + "\n";
    text += "\n========================================\n";
    text += "Generated by DataLens AI Analytics\n";

    const blob = new Blob([text], { type: "text/plain" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = `datalens-insights-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(a.href);
    toast.success("Report downloaded");
  };

  if (!datasetId) {
    return (
      <div className="p-6 flex flex-col items-center justify-center py-24 text-center">
        <p className="text-surface-400 mb-4">Select a dataset to generate AI insights.</p>
      </div>
    );
  }

  return (
    <div className="p-6 space-y-5">
      {/* Header with history toggle */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          {!insight && !loading && !error && (
            <button onClick={generate} className="px-6 py-3 bg-accent hover:bg-accent-dark text-white rounded-xl font-semibold text-sm transition shadow-lg shadow-accent/20">
              Generate Insights
            </button>
          )}
          {history.length > 0 && (
            <button
              onClick={() => setShowHistory(!showHistory)}
              className="px-4 py-2.5 bg-surface-800 hover:bg-surface-700 border border-surface-700 rounded-xl text-sm text-surface-200 font-medium transition"
            >
              {showHistory ? "Hide" : "Show"} History ({history.length})
            </button>
          )}
        </div>
        {insight && (
          <div className="flex gap-2">
            <button onClick={downloadPDF} className="px-4 py-2 bg-surface-800 hover:bg-surface-700 border border-surface-700 rounded-xl text-sm font-medium transition">
              Download Report
            </button>
            <button onClick={generate} className="px-4 py-2 bg-accent hover:bg-accent-dark text-white rounded-xl text-sm font-medium transition">
              Regenerate
            </button>
          </div>
        )}
      </div>

      {/* History panel */}
      {showHistory && (
        <div className="bg-surface-900 border border-surface-800 rounded-2xl p-5">
          <h3 className="text-base font-semibold mb-4">Insight History</h3>
          {history.length === 0 ? (
            <p className="text-sm text-surface-500">No previous insights.</p>
          ) : (
            <div className="space-y-2 max-h-60 overflow-y-auto">
              {history.map((h) => (
                <button
                  key={h._id}
                  onClick={() => loadHistoryItem(h._id)}
                  className="w-full text-left p-3 bg-surface-950 rounded-xl border border-surface-800 hover:border-accent/30 transition"
                >
                  <div className="flex items-center justify-between">
                    <span className="text-sm text-surface-300 truncate max-w-md">{h.summary.slice(0, 80)}...</span>
                    <span className="text-[10px] px-2 py-0.5 rounded-full bg-surface-800 text-surface-400 ml-2 whitespace-nowrap">{h.model}</span>
                  </div>
                  <p className="text-xs text-surface-500 mt-1">{new Date(h.createdAt).toLocaleString()}</p>
                </button>
              ))}
            </div>
          )}
        </div>
      )}

      {/* Loading */}
      {loading && (
        <div className="space-y-4">
          <div className="bg-surface-900 border border-surface-800 rounded-2xl p-6 space-y-3">
            <Skeleton width="160px" height="20px" />
            <Skeleton height="60px" />
          </div>
          <div className="bg-surface-900 border border-surface-800 rounded-2xl p-6 space-y-3">
            <Skeleton width="100px" height="20px" />
            <Skeleton height="40px" /><Skeleton height="40px" /><Skeleton height="40px" />
          </div>
        </div>
      )}

      {/* Error */}
      {error && (
        <div className="flex flex-col items-center justify-center py-16 text-center">
          <div className="w-16 h-16 rounded-2xl bg-red-500/10 flex items-center justify-center mb-4 text-red-400">
            <svg className="w-8 h-8" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}><path strokeLinecap="round" strokeLinejoin="round" d="M12 9v3.75m9-.75a9 9 0 11-18 0 9 9 0 0118 0zm-9 3.75h.008v.008H12v-.008z" /></svg>
          </div>
          <p className="text-surface-300 mb-1">Failed to generate insights</p>
          <p className="text-sm text-surface-500 mb-4">{error}</p>
          <button onClick={generate} className="px-6 py-2 bg-surface-800 hover:bg-surface-700 border border-surface-700 rounded-xl text-sm font-medium transition">Try Again</button>
        </div>
      )}

      {/* Insights content */}
      {insight && !loading && (
        <>
          <div className="bg-surface-900 border border-surface-800 rounded-2xl p-6">
            <div className="flex items-start gap-4">
              <div className="w-11 h-11 rounded-xl bg-accent/10 flex items-center justify-center flex-shrink-0 text-accent">
                <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 00-3.375-3.375h-1.5A1.125 1.125 0 0113.5 7.125v-1.5a3.375 3.375 0 00-3.375-3.375H8.25m0 12.75h7.5m-7.5 3H12M10.5 2.25H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 00-9-9z" /></svg>
              </div>
              <div className="flex-1">
                <div className="flex items-center gap-2 mb-2">
                  <h3 className="text-base font-semibold">Executive Summary</h3>
                  <span className="text-[10px] px-2 py-0.5 rounded-full bg-surface-800 text-surface-400">{insight.model}</span>
                  {insight.fromCache && <span className="text-[10px] px-2 py-0.5 rounded-full bg-amber-500/10 text-amber-400">cached</span>}
                </div>
                <p className="text-sm text-surface-300 leading-relaxed">{insight.summary}</p>
              </div>
            </div>
          </div>

          <div className="bg-surface-900 border border-surface-800 rounded-2xl p-6">
            <div className="flex items-center gap-3 mb-4">
              <div className="w-11 h-11 rounded-xl bg-blue-500/10 flex items-center justify-center text-blue-400">
                <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M2.25 18L9 11.25l4.306 4.307a11.95 11.95 0 015.814-5.519l2.74-1.22m0 0l-5.94-2.28m5.94 2.28l-2.28 5.941" /></svg>
              </div>
              <h3 className="text-base font-semibold">Key Trends</h3>
            </div>
            <div className="space-y-3">
              {insight.trends.map((t, i) => (
                <div key={i} className="flex items-start gap-3 p-3 bg-surface-950 rounded-xl border border-surface-800">
                  <span className="w-5 h-5 rounded-full bg-blue-500/10 flex items-center justify-center flex-shrink-0 mt-0.5 text-blue-400 text-xs font-bold">{i + 1}</span>
                  <p className="text-sm text-surface-300 leading-relaxed">{t}</p>
                </div>
              ))}
            </div>
          </div>

          <div className="bg-surface-900 border border-surface-800 rounded-2xl p-6">
            <div className="flex items-center gap-3 mb-4">
              <div className="w-11 h-11 rounded-xl bg-red-500/10 flex items-center justify-center text-red-400">
                <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126zM12 15.75h.007v.008H12v-.008z" /></svg>
              </div>
              <h3 className="text-base font-semibold">Anomalies Detected</h3>
            </div>
            <div className="space-y-3">
              {insight.anomalies.map((a, i) => (
                <div key={i} className="flex items-start gap-3 p-3 bg-surface-950 rounded-xl border border-surface-800">
                  <span className="w-5 h-5 rounded-full bg-red-500/10 flex items-center justify-center flex-shrink-0 mt-0.5 text-red-400 text-xs font-bold">!</span>
                  <p className="text-sm text-surface-300 leading-relaxed">{a}</p>
                </div>
              ))}
            </div>
          </div>

          <div className="bg-surface-900 border border-surface-800 rounded-2xl p-6">
            <div className="flex items-center gap-3 mb-4">
              <div className="w-11 h-11 rounded-xl bg-amber-500/10 flex items-center justify-center text-amber-400">
                <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M12 18v-5.25m0 0a6.01 6.01 0 001.5-.189m-1.5.189a6.01 6.01 0 01-1.5-.189m3.75 7.478a12.06 12.06 0 01-4.5 0m3.75 2.383a14.406 14.406 0 01-3 0M14.25 18v-.192c0-.983.658-1.823 1.508-2.316a7.5 7.5 0 10-7.517 0c.85.493 1.509 1.333 1.509 2.316V18a2 2 0 002 2h.44a2 2 0 002-2v-.18a2 2 0 011-1.73l-.43-.25a2 2 0 01-2 0l-.43.25a2 2 0 00-1 1.73V18" /></svg>
              </div>
              <h3 className="text-base font-semibold">Recommendations</h3>
            </div>
            <div className="space-y-3">
              {insight.recommendations.map((r, i) => (
                <div key={i} className="flex items-start gap-3 p-3 bg-surface-950 rounded-xl border border-surface-800">
                  <span className="w-5 h-5 rounded-full bg-amber-500/10 flex items-center justify-center flex-shrink-0 mt-0.5 text-amber-400 text-xs font-bold">{i + 1}</span>
                  <p className="text-sm text-surface-300 leading-relaxed">{r}</p>
                </div>
              ))}
            </div>
          </div>
        </>
      )}
    </div>
  );
}

export default function InsightsPage() {
  return (
    <Suspense fallback={<div className="p-6"><div className="w-8 h-8 border-2 border-accent border-t-transparent rounded-full animate-spin mx-auto mt-24" /></div>}>
      <InsightsContent />
    </Suspense>
  );
}